# ========================================================
# 1. KONFIGURASI UTAMA (atabikm.me)
# ========================================================
server {
    listen 80;
    server_name atabikm.me www.atabikm.me;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name atabikm.me www.atabikm.me;

    ssl_certificate /etc/letsencrypt/live/atabikm.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/atabikm.me/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /var/www/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wms_app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}

# ========================================================
# 2. KONFIGURASI SUBDOMAIN (chitchat.atabikm.me)
# ========================================================
server {
    listen 80;
    server_name chitchat.atabikm.me;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# 2. Server HTTPS Utama untuk ChitChat
server {
    listen 443 ssl;
    server_name chitchat.atabikm.me;

    error_log  /var/log/nginx/chitchat_error.log;
    access_log /var/log/nginx/chitchat_access.log;

    # DI SINI PERUBAHAN UTAMANYA: Arahkan ke sertifikat chitchat yang baru saja terbit
    ssl_certificate /etc/letsencrypt/live/chitchat.atabikm.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/chitchat.atabikm.me/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        try_files $uri /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass chitchat_app_production:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/chitchat/public$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
