server {
    listen 80;
    server_name atabikm.me www.atabikm.me;

    # Redirect otomatis dari HTTP ke HTTPS
    location / {
        return 301 https://$host$request_uri;
    }

    # Tetap sediakan jalan untuk renewal sertifikat di masa depan
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}

server {
    listen 443 ssl;
    server_name atabikm.me www.atabikm.me;

    # LOKASI SERTIFIKAT (Pastikan nama domain sesuai)
    ssl_certificate /etc/letsencrypt/live/atabikm.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/atabikm.me/privkey.pem;

    # Optimasi Keamanan SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /var/www/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wms_app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
