name: Deploy to VPS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- TARUH DI SINI ---
      - name: Debug Secret Check
        run: |
          echo "Username length: ${#USER}"
          echo "Token length: ${#TOKEN}"
        env:
          USER: ${{ secrets.DOCKERHUB_USERNAME }}
          TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      # ---------------------

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wms-app:latest
  deploy-to-vps:
    needs: build-and-push # Tunggu build selesai baru deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH to VPS and Update Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            # Masuk ke folder project (sesuaikan)
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
            docker stop my-container || true
            docker rm my-container || true
            docker run -d --name my-container -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
